POST http://localhost:5000/auth/register
content-type: application/json

{
    "clave": "12345",   
    "nombres": "Luis",
    "apellidos": "Mora",
    "nombreUsuario": "qrqfvsa",
    "email": "luis.morests.test.t.co",
    "fecha_nac": "2003/1100/"
}

###
POST http://localhost:5000/auth/register
content-type: application/json

{
    "clave": "12345",
    "nombres": "Carlos",
    "apellidos": "2",
    "email": "prueba@gmail.edu.co",
    "fecha_nac": "2024-02-29"
}
###
POST http://localhost:5000/auth/login
content-type: application/json

{
    "clave": "12345",
    "email": "andrey12mora@gmail.com"
   
}
###
POST http://localhost:5000/auth/verification/21c705b6-a8fc-4a1d-884f-bcbd5f68a138
content-type: application/json

{
    "codigo": "VCFA13"
}
###
POST http://localhost:5000/auth/resendcode/21c705b6-a8fc-4a1d-884f-bcbd5f68a138

###
POST http://localhost:5000/auth/register/empleado
content-type: application/json
{
 "rol": "admin"
}
###
PUT http://localhost:5000/tickets/aceptar/09e408ee-a22f-4580-a452-cc8c0b11d47e
#admin
# 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzdWFyaW8iOiIwNmE2OTI1MS02ZTc0LTQzM2ItYjZjOS01YTYwZGM0ODM1YWMiLCJub21icmVzIjoiQ2FybG9zIiwiYXBlbGxpZG9zIjoiMiIsImVtYWlsIjoiYUBnbWFpbC5lZHUuY28iLCJpYXQiOjE3MTQzNTUxMTR9.yClFPEGoLORoK_T9AYD5sL8waXOhbht0iIbG_5pdaec
#cliente
# authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzdWFyaW8iOiI5YzJkMWUyYy04NzVmLTRmZGUtYjE2NS1kMzc3OGQ1OWI5ZWUiLCJub21icmVzIjoiQ2FybG9zIiwiYXBlbGxpZG9zIjoiMiIsImVtYWlsIjoiYWJAZ21haWwuZWR1LmNvIiwiaWF0IjoxNzE0MzQ4MjkwfQ.SWQr_3tz_HwFyfbkHfkmqPtVUdlLvhwRjWSDBdRxmDM
Content-Type: application/json

{
    "prioridad": "media",
    "idclasificacion": "3" 
}


###
POST http://localhost:5000/tickets/
Content-Type: application/json

{
    "email": "prueba@gmail.edu.co",
    "asunto": "Mi asunto",
    "contenido": "Esto me paso y pues aja"
}

###
get http://localhost:5000/componentes/especificaciones-categoria/3







