POST http://localhost:5000/auth/register
content-type: application/json

{
    "clave": "12345",   
    "nombres": "Luis",
    "apellidos": "Mora",
    "nombreUsuario": "qrqfvsa",
    "email": "luis.morests.test.t.co",
    "fecha_nac": "2003/1100/"
}

###
POST http://localhost:5000/auth/register
content-type: application/json

{
    "clave": "12345",
    "nombres": "Carlos",
    "apellidos": "2",
    "email": "a@gmail.edu.co",
    "fecha_nac": "2024-02-29"
}
###
POST http://localhost:5000/auth/login
content-type: application/json

{
    "clave": "' 1=1 --",
    "email": "c@com.co' OR 1=1 /*"
   
}
###
POST http://localhost:5000/auth/verification/21c705b6-a8fc-4a1d-884f-bcbd5f68a138
content-type: application/json

{
    "codigo": "VCFA13"
}
###
POST http://localhost:5000/auth/resendcode/21c705b6-a8fc-4a1d-884f-bcbd5f68a138

###
get http://localhost:5000/tickets/gestionar
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzdWFyaW8iOiIzYWIzNTYwOC01MDkyLTRmMDEtOTY1MS1jYWMzNGQzOTIwOGIiLCJub21icmVzIjoiQ2FybG9zIERhdmlkIiwiYXBlbGxpZG9zIjoiUm9tZXJvIHJlc3RyZXBvIiwiZW1haWwiOiJlbXBsZWFkb0BnbWFpbC5lZHUuY29tIiwibm9tYnJlVXN1YXJpbyI6ImVtcGxlYWRvIiwiaWF0IjoxNzE0ODAwNzcyfQ.oQjd-lpF4Hwas2GyyQx8y-FXHoqjhKB4FkgwETMTJ70

###
PUT http://localhost:5000/tickets/aceptar/56eec0e9-54f7-450a-ae75-622659436d55
#admin
# 
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzdWFyaW8iOiIzYWIzNTYwOC01MDkyLTRmMDEtOTY1MS1jYWMzNGQzOTIwOGIiLCJub21icmVzIjoiQ2FybG9zIERhdmlkIiwiYXBlbGxpZG9zIjoiUm9tZXJvIHJlc3RyZXBvIiwiZW1haWwiOiJlbXBsZWFkb0BnbWFpbC5lZHUuY29tIiwibm9tYnJlVXN1YXJpbyI6ImVtcGxlYWRvIiwiaWF0IjoxNzE0ODAwNzcyfQ.oQjd-lpF4Hwas2GyyQx8y-FXHoqjhKB4FkgwETMTJ70
#cliente
# authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzdWFyaW8iOiI5YzJkMWUyYy04NzVmLTRmZGUtYjE2NS1kMzc3OGQ1OWI5ZWUiLCJub21icmVzIjoiQ2FybG9zIiwiYXBlbGxpZG9zIjoiMiIsImVtYWlsIjoiYWJAZ21haWwuZWR1LmNvIiwiaWF0IjoxNzE0MzQ4MjkwfQ.SWQr_3tz_HwFyfbkHfkmqPtVUdlLvhwRjWSDBdRxmDM
Content-Type: application/json

{
    "prioridad": "media",
    "idtipo_servicio": "3" 
}


###
POST http://localhost:5000/tickets/email
Content-Type: application/json

{
    "email": "prueba@gmail.edu.co",
    "asunto": "Mi asunto",
    "contenido": "Esto me paso y pues aja"
}

###
get http://localhost:5000/componentes/especificaciones-categoria/3







