POST http://localhost:5000/auth/register
content-type: application/json

{
    "clave": "12345",   
    "nombres": "Luis",
    "apellidos": "Mora",
    "nombreUsuario": "qrqfvsa",
    "email": "luis.morests.test.t.co",
    "fecha_nac": "2003/1100/"
}

###
POST http://localhost:5000/auth/register
content-type: application/json

{
    "clave": "12345",
    "nombres": "Carlos",
    "apellidos": "2",
    "email": "a@gmail.edu.co",
    "fecha_nac": "2024-02-29"
}
###
POST http://localhost:5000/auth/login
content-type: application/json

{
    "clave": "12345",
    "email": "a@gmail.edu.co"
   
}
###
POST http://localhost:5000/auth/verification/b405b3b2-5a6d-4c6e-a0c5-cb3c6f581793
content-type: application/json

{
    "codigo": "s0iw2g"
}
###
POST http://localhost:5000/auth/resendcode/8c13016d-886a-4269-b83a-91d534f75a08

###
POST http://localhost:5000/auth/register/empleado
content-type: application/json
{
 "rol": "admin"
}

###
POST http://localhost:5000/auth/register/empleado
#authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZHVzdWFyaW8iOiJiNjMwZmZhYS1iYTlhLTQyYjktYmU0MC02OGViYWFkZmMxNDUiLCJub21icmVzIjoiQ2FybG9zIiwiYXBlbGxpZG9zIjoiMiIsImVtYWlsIjoiYUBnbWFpbC5lZHUuY28iLCJpYXQiOjE3MTM0NTYzNjF9.KWxJzqjcnaiI3aspzGUCseqDG8eetQ-OTLA6LEJVWdI

###
get http://localhost:5000/componentes/8c13016d-886a-4269-b83a-91d534f75a08







