version: "3.1"

services:
  test-db:
    image: postgres
    restart: always
    ports:
      - 2345:5432
    environment:
      POSTGRES_USER:     test
      POSTGRES_PASSWORD: test
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER:     dev
      POSTGRES_PASSWORD: dev
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d